apiVersion: v1
kind: Service
metadata:
  name: eventstore-service
spec:
  type: NodePort
  ports:
  - nodePort: 31317
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: eventstore
